name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Copy .env
        working-directory: apps/backend
        run: |
          echo "DATABASE_URL=mysql://testuser:testpass@localhost:3306/testdb" > .env

      - name: Install dependencies
        run: bun install

      - name: Run migrations
        run: bun run migrate:deploy

      - name: Run seeders
        run: bun run seed

      - name: Run tests
        run: bun run test
